<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "{{%posts}}".
 *
 * @property int $id
 * @property int $user_id
 * @property string $date_created
 * @property string $date_updated
 * @property string $body
 * @property string $title
 *
 * @property Comments[] $comments
 * @property Users $user
 */
class Posts extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%posts}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id', 'body', 'title'], 'required'],
            [['user_id'], 'integer'],
            [['date_created', 'date_updated'], 'safe'],
            [['body'], 'string'],
            [['title'], 'string', 'max' => 255],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => Userdb::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'date_created' => 'Date Created',
            'date_updated' => 'Date Updated',
            'body' => 'Body',
            'title' => 'Title',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getComments()
    {
        return $this->hasMany(Comments::className(), ['post_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(Userdb::className(), ['id' => 'user_id']);
    }

    public function beforeSave($insert)
    {
        if ($insert) {
//            $data = date('Y-m-d ') . (date('H') - 1) . date(':i:s');
            //todo: conf apache, do not use such date
            $date = date('Y-m-d H:i:s');
            $this->date_created = $this->date_updated = $date;

        } else {

        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
