<?php
/**
 * Created by PhpStorm.
 * User: 1
 * Date: 01.03.2019
 * Time: 19:21
 */

namespace app\models;

use Yii;
use yii\base\Model;
use yii\helpers\Html;

/**
 * ContactForm is the model behind the contact form.
 */
class resetPassword extends Model
{
    public $email;
    public $captcha;

    public function rules()
    {
        return [
            [['email', 'captcha'], 'required'],
            ['email', 'email'],
            ['captcha', 'captcha']
        ];
    }

    public function attributeLabels()
    {
//    return parent::attributeLabels(); // TODO: Change the autogenerated stub
        return [
            'email' => 'Імейл',
            'captcha' => 'Введіть код з рисунка'
        ];
    }

    public function resetPassword()
    {
        if ($this->validate()) {
            $user = Userdb::findOne(['email' => $this->email]);
            if (!empty($user->email)) {

                Yii::$app->mailer->compose()
                    ->setTo($this->email)
                    ->setFrom(Yii::$app->params['adminEmail'])
                    ->setSubject('reset password')
//                  ->setHtmlBody(Html::a('visit it', [
//                     Yii::$app->params['baseUrl'] . '/users/reset-password',
//                     'token' => $user->pass_reset_token]))
//
//                     ->setHtmlBody( '<a href="http://web6yii/users/reset-password&token=' . $user->pass_reset_token . '">visit</a>')
                    ->setHtmlBody('<a href="' . Yii::$app->params['baseUrl'] .
                        '/users/reset-password&token=' . $user->pass_reset_token . '">visit</a>')
                    ->send();

                return true;
            } else {
                return false;
            }
        }
        return false;
    }
}